import React, { useEffect, useState } from 'react'
import projects from '../../../shared/projects.json'
import Icon from '../components/Icon'

const tracks = [
  { level: 'beginner', icon: 'code', title: 'SQL foundations', description: 'Select, filter, and sort. Build confidence with the essentials.', topics: ['SELECT', 'WHERE', 'ORDER BY'], color: 'indigo' },
  { level: 'intermediate', icon: 'database', title: 'Connect & analyze', description: 'Join related data and turn rows into meaningful summaries.', topics: ['JOINs', 'GROUP BY', 'HAVING'], color: 'teal' },
  { level: 'advanced', icon: 'chart', title: 'Think like an analyst', description: 'Break complex questions into clear, purposeful queries.', topics: ['CTEs', 'Subqueries', 'Reporting'], color: 'amber' },
]
function readGoal(key) {
  try { const value = Number(localStorage.getItem(key)); return [1, 3, 5].includes(value) ? value : 3 } catch { return 3 }
}

export default function LearningDashboard({ account, lessons, questionCount, completionCount, nextLesson, progress, navigate, openLesson, openPractice, openProject, openQuestion, ping }) {
  const goalKey = `sqlmaster:daily-goal:${account?.user.id || 'guest'}`
  const [goal, setGoal] = useState(() => readGoal(goalKey))
  const [goalError, setGoalError] = useState('')
  useEffect(() => { setGoal(readGoal(goalKey)); setGoalError('') }, [goalKey])
  const todayAttempts = account?.activity?.todayAttempts || 0
  const recentMiss = account?.recentAttempts?.find(attempt => !attempt.correct)
  const firstName = account?.user.name?.split(' ')[0]
  const percent = lessons.length ? Math.round(completionCount / lessons.length * 100) : 0
  const resume = () => recentMiss ? openQuestion({ id: recentMiss.exerciseId, track: recentMiss.track }) : nextLesson ? openLesson({ id: nextLesson.id }) : navigate('lessons')
  const activity = account?.activity?.days?.slice(-7) || Array.from({ length: 7 }, (_, index) => ({ date: new Date(Date.now() - (6 - index) * 86400000).toISOString().slice(0, 10), attempts: 0 }))
  function changeGoal(value) {
    setGoal(value)
    try { localStorage.setItem(goalKey, String(value)); setGoalError('') } catch { setGoalError('Goal set for this visit. Browser storage is unavailable.') }
  }

  return <div className="learning-home">
    <div className="home-heading"><div><p className="eyebrow">YOUR LEARNING WORKSPACE</p><h1>{firstName ? `Good to see you, ${firstName}.` : 'Big ambitions. One query at a time.'}</h1><p className="muted">{account ? 'Make a little progress today. Your next breakthrough starts here.' : 'Learn SQL, work with real datasets, and build skills you can put to use.'}</p></div><span className="today-label"><Icon name="clock" size={16} />{new Date().toLocaleDateString(undefined, { month: 'short', day: 'numeric', weekday: 'short' })}</span></div>
    <div className="home-hero-grid"><section className="learning-hero"><div className="hero-grid-lines" aria-hidden="true" /><div className="learning-hero-copy"><span className="hero-kicker"><span />LEARN. QUERY. GROW.</span><h2>A little practice.<br />A lot of possibility.</h2><p>From your first SELECT to your next career move. Learn by solving one good question at a time.</p><button className="hero-primary" onClick={resume}>{account ? 'Continue learning' : 'Start your learning path'}<Icon name="arrow" size={18} /></button><a href="#/practice" className="hero-secondary">Explore the practice library <Icon name="arrowUp" size={15} /></a></div><div className="hero-query-card" aria-label="Example query using the practice dataset"><div className="hero-query-title"><span><i /><i /><i /></span><small>your_next_step.sql</small></div><pre><span className="sql-keyword">SELECT</span> name, score<br /><span className="sql-keyword">FROM</span> students<br /><span className="sql-keyword">WHERE</span> score &gt;= <span className="sql-value">85</span><br /><span className="sql-keyword">ORDER BY</span> score <span className="sql-keyword">DESC</span>;</pre><div className="query-card-footer"><Icon name="code" size={15} /><span>Small queries. Lasting skills.</span><span className="query-caret" /></div></div></section>
    <section className="daily-goal card"><div className="section-header"><h2>Your daily goal</h2><Icon name="target" /></div><div className="goal-ring" style={{ '--goal-angle': `${Math.min(todayAttempts / goal, 1) * 360}deg` }} role="img" aria-label={`${todayAttempts} of ${goal} daily submissions`}><div><strong>{todayAttempts}<small> / {goal}</small></strong><span>queries submitted</span></div></div><p>{todayAttempts >= goal ? 'Goal reached. Keep the momentum going!' : account ? `${Math.max(0, goal - todayAttempts)} more to reach your goal.` : 'Choose a small goal. Build a lasting habit.'}</p><div className="goal-options" aria-label="Daily submission goal">{[1, 3, 5].map(value => <button key={value} aria-pressed={value === goal} className={value === goal ? 'selected' : ''} onClick={() => changeGoal(value)}>{value} {value === 1 ? 'query' : 'queries'}</button>)}</div><small>{goalError || 'Goal saved on this browser · Daily totals use UTC'}</small></section></div>
    <section className="overview-metrics" aria-label="Your learning statistics">{[['flame', account?.stats.streak || 0, 'day practice streak', 'amber'], ['check', account?.stats.solved || 0, 'challenges solved', 'teal'], ['book', `${completionCount} / ${lessons.length}`, 'lessons completed', 'indigo'], ['trophy', account?.score || 0, 'experience points', 'rose']].map(([icon, value, label, color]) => <div key={label} className="overview-metric"><span className={`metric-icon ${color}`}><Icon name={icon} /></span><div><strong>{value}</strong><span>{label}</span></div></div>)}</section>
    <div className="home-content-grid"><div className="home-main-stack"><section><div className="section-header"><div><p className="eyebrow">A CLEAR WAY FORWARD</p><h2>Your learning path</h2></div><a href="#/lessons">View curriculum <Icon name="arrow" size={15} /></a></div><div className="path-cards">{tracks.map((track, index) => {
      const list = lessons.filter(lesson => lesson.level === track.level)
      const done = list.filter(lesson => progress.some(item => item.lessonId === lesson.id && item.status === 'completed')).length
      return <article className="learning-path-card" key={track.level}><div className={`path-card-art ${track.color}`}><Icon name={track.icon} size={30} /><span>0{index + 1}</span></div><div className="path-card-copy"><span className={`difficulty ${track.level}`}>{track.level}</span><h3>{track.title}</h3><p>{track.description}</p><div className="skill-tags">{track.topics.map(topic => <span key={topic}>{topic}</span>)}</div><div className="path-card-progress"><span>{done} of {list.length} lessons</span><strong>{list.length ? Math.round(done / list.length * 100) : 0}%</strong></div><progress max={list.length || 1} value={done} aria-label={`${track.level} lesson completion`} /><button className="ghost" onClick={() => openLesson({ level: track.level })}>{done ? 'Continue path' : 'Explore path'}<Icon name="arrow" size={16} /></button></div></article>
    })}</div></section>
    <section className="resume-learning card"><span className="resume-icon"><Icon name={recentMiss ? 'code' : 'book'} size={24} /></span><div><p className="eyebrow">{recentMiss ? 'WORTH ANOTHER TRY' : percent === 100 ? 'YOUR NEXT CHALLENGE' : 'PICK UP FROM HERE'}</p><h3>{recentMiss?.title || (percent === 100 ? 'Take your skills into a project' : nextLesson?.title || 'Read your first table')}</h3><p className="muted">{recentMiss ? `Revisit ${recentMiss.topic} and try a different approach.` : percent === 100 ? 'Connect what you learned to a complete business brief.' : nextLesson?.summary}</p></div><button className="ghost" onClick={percent === 100 && !recentMiss ? () => navigate('projects') : resume}>{percent === 100 && !recentMiss ? 'View projects' : 'Continue'}<Icon name="arrow" size={16} /></button></section>
    <section><div className="section-header"><div><p className="eyebrow">LEARN IN CONTEXT</p><h2>From practice to projects</h2></div><a href="#/projects">All projects <Icon name="arrow" size={15} /></a></div><div className="home-projects">{projects.slice(0, 2).map(project => <button key={project.id} className="home-project-card" onClick={() => openProject(project.id)}><span className={`project-tile ${project.color}`}><Icon name={project.icon} size={27} /></span><span><small>{project.category}</small><strong>{project.title}</strong><span>{project.steps.length} guided tasks · {project.minutes} min estimate</span></span><Icon name="arrowUp" size={18} /></button>)}</div></section></div>
    <aside className="home-side-stack"><section className="card weekly-activity"><div className="section-header"><h2>This week</h2><Icon name="chart" size={18} /></div><strong className="weekly-total">{account?.activity?.weekAttempts || 0}<span> submissions</span></strong><div className="week-bars">{activity.map(day => <div key={day.date}><div className="week-bar-track"><span style={{ height: `${day.attempts ? Math.max(12, day.attempts / Math.max(5, ...activity.map(item => item.attempts)) * 100) : 0}%` }} title={`${day.date}: ${day.attempts} submissions`} /></div><small>{new Date(`${day.date}T12:00:00Z`).toLocaleDateString(undefined, { weekday: 'narrow', timeZone: 'UTC' })}</small><span className="sr-only">{day.date}: {day.attempts} submissions</span></div>)}</div><p className="muted">Consistency starts with showing up. Each submission counts.</p><a href="#/progress">See your activity <Icon name="arrow" size={15} /></a></section><section className="interview-promo"><span className="promo-icon"><Icon name="briefcase" size={22} /></span><p className="eyebrow">YOUR NEXT CHAPTER</p><h2>Get interview ready.</h2><p>Practice realistic SQL questions for analyst, developer, and data engineer roles.</p><button className="ghost" onClick={() => navigate('interviews')}>Explore interview prep<Icon name="arrow" size={15} /></button></section><section className="practice-prompt"><Icon name="spark" size={20} /><h3>{account?.weakTopics?.[0] ? `Strengthen your ${account.weakTopics[0].topic}` : 'Make room for discovery'}</h3><p className="muted">{account?.weakTopics?.[0] ? 'A focused practice session can turn a tricky topic into a new strength.' : `${Number(questionCount || 0).toLocaleString()} practice challenges are ready to explore.`}</p><button className="text-button" onClick={() => openPractice(account?.weakTopics?.[0] ? { topic: account.weakTopics[0].topic } : {})}>Find a challenge <Icon name="arrow" size={15} /></button></section></aside></div>
    <footer className="page-footer"><span>SQL Master · Build understanding, one query at a time.</span><span>{ping === 'pong' ? 'Ready when you are' : 'Lessons available offline'}</span></footer>
  </div>
}
